### ISSUE TITLE
Is it possible to run quick fix? 

### ISSUE THREAD

**Issue by Migacz85** [heavenshell/vim-textlint#4]
Is it possible to use quick fix inside vim when there is proposed solution?

**Comment by heavenshell** [comment]
@Migacz85 
Sorry for if my understanding was wrong.
Do you want auto fix('textlint --fix') option?

Currently not implemented.

**Comment by Migacz85** [comment]
Yes, if you will implement I will used it :-)

**Comment by heavenshell** [comment]
@Migacz85 Thx for request.
Fumm, it's not easy but I'll add to my todo list.
So please stay tuned 😉

**Comment by heavenshell** [comment]
@Migacz85 
Hey, I added autofix feature.
You can use `TextlintFix` if setting rules are fixable.
